name: POF_BOOK
channels:
- conda-forge
- nodefaults
dependencies:
- pandas
- xarray
- netcdf4
- cdsapi
- cartopy
- numpy
- joblib
- matplotlib
- xgboost
- scikit-learn
- dask
- jupyterlab
- jupyter-book
- ipykernel
- cftime
- pip
- python=3.14
